# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

version: "2.1"

services:
  dgc-api:
    image: dgc-api
    build:
      context: .
      dockerfile: api/Dockerfile-installed-${DISTRO}
    container_name: dgc-api
    expose:
      - 9001
    ports:
      - 9001:9001
    command: cargo run
    build:
      context: .
    environment:
      RUST_BACKTRACE: 1
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: 9001
      VALIDATOR_URL: tcp://validator:9004
      DATABASE_URL: postgres://dgc:dgc@dgc-db:5432/dgc_identity

  dgc-swagger-ui:
    image: dgc-swagger-ui
    build:
      context: .
      dockerfile: api/Dockerfile-swagger-ui
    container_name: dgc-swagger-ui
    expose:
      - 80
    ports:
      - 9002:80

  dgc-db:
    image: dgc-db
    build:
      context: db/
      dockerfile: Dockerfile
    container_name: dgc-db
    environment:
      POSTGRES_DB: dgc_identity
      POSTGRES_USER: dgc
      POSTGRES_PASSWORD: dgc
    ports:
      - 5432:5432

  dgc-adminer:
    image: adminer
    container_name: dgc-adminer
    links:
      - dgc-db:db
    ports:
      - 9003:8080

  dgc-client:
    image: dgc-client
    build:
      context: .
      dockerfile: cli/Dockerfile-installed-${DISTRO}
    container_name: dgc-client
    entrypoint: "bash -c \"\
      sawtooth keygen && \
      tail -f /dev/null \
      \""

  validator:
    image: hyperledger/sawtooth-validator:latest
    container_name: dgc-validator
    expose:
      - 9004
    ports:
      - "9004:9004"
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:9005 \
          --bind component:tcp://eth0:9004 \
          --bind network:tcp://eth0:9005 \
          --bind consensus:tcp://eth0:5050 \
        \""

  rest-api:
    image: hyperledger/sawtooth-rest-api:latest
    container_name: dgc-sawtooth-rest-api
    expose:
      - 9008
    ports:
      - "9008:9008"
    entrypoint: sawtooth-rest-api --connect tcp://validator:9004 --bind rest-api:9008 -vv

  shell:
    image: hyperledger/sawtooth-shell:latest
    container_name: dgc-shell
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:latest
    container_name: dgc-settings-tp
    entrypoint: settings-tp -vv --connect tcp://validator:9004

  devmode-rust:
    image: hyperledger/sawtooth-devmode-engine-rust:latest
    container_name: sawtooth-devmode-engine-rust
    depends_on:
      - validator
    command: |
        devmode-engine-rust -v --connect tcp://validator:5050
    stop_signal: SIGKILL

  dgc-tp:
    image: dgc-tp
    build:
      context: .
      dockerfile: tp/Dockerfile-installed-${DISTRO}
    container_name: dgc-tp
    entrypoint: "bash -c \"\
        dgc-tp -vv -C tcp://validator:9004 \
        \""

  dgc-sde-service:
    image: dgc-sde-service
    build:
      context: .
      dockerfile: state_delta_export/Dockerfile-installed-${DISTRO}
    container_name: dgc-sde-service
    environment:
      DATABASE_URL: postgres://dgc:dgc@dgc-db:5432/dgc
    entrypoint: "bash -c \"dgc-sde -vv -c tcp://validator:9004\""
    depends_on:
      - validator
      - rest-api
      - dgc-db
