# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

version: "2.1"

volumes:
  keys:

services:
  validator:
    image: hyperledger/sawtooth-validator
    container_name: validator
    volumes:
      - keys:/keys
    expose:
      - 4004
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen && \
        cp /etc/sawtooth/keys/* /keys/ && \
        sawset genesis  -k /etc/sawtooth/keys/validator.priv && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.swa.administrators=$$(cat /etc/sawtooth/keys/validator.pub) \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""

  rest-api:
    image: hyperledger/sawtooth-rest-api
    container_name: rest-api
    expose:
      - 8008
    ports:
      - "8008:8008"
    entrypoint: sawtooth-rest-api --connect tcp://validator:4004 --bind rest-api:8008 -vv

  shell:
    image: hyperledger/sawtooth-shell
    container_name: shell
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  settings-tp:
    image: hyperledger/sawtooth-settings-tp
    container_name: settings-tp
    entrypoint: settings-tp -vv --connect tcp://validator:4004

  devmode-rust:
    image: hyperledger/sawtooth-devmode-engine-rust
    container_name: devmode-engine
    depends_on:
      - validator
    command: |
      devmode-engine-rust -v --connect tcp://validator:5050
    stop_signal: SIGKILL

  sabre-tp:
    image: hyperledger/sawtooth-sabre-tp
    container_name: sabre-tp
    entrypoint: sawtooth-sabre -vvv -C tcp://validator:4004

  sabre-cli:
    image: hyperledger/sawtooth-sabre-cli
    container_name: sabre-cli
    volumes:
      - keys:/keys
      - .:/project
    entrypoint: "bash -c \"\
      tail -f /dev/null \
      \""

  dgc-api:
    image: dgc-api
    container_name: dgc-api
    volumes:
      - .:/project
    expose:
      - 9001
    ports:
      - 9001:9001
    entrypoint: "bash -c \"\
      cd /project/api && \
      cargo build && \
      tail -f /dev/null \
      \""
    build:
      context: ./api/
    environment:
      RUST_BACKTRACE: 1
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: 9001
      VALIDATOR_URL: tcp://validator:9004
      DATABASE_URL: postgres://dgc:dgc@dgc-db:5432/dgc

  dgc-swagger-ui:
    image: dgc-swagger-ui
    container_name: dgc-swagger-ui
    volumes:
      - .:/project
    expose:
      - 80
    ports:
      - 9002:80
    build:
      context: .
      dockerfile: ./api/Dockerfile-swagger-ui

  dgc-db:
    image: dgc-db
    container_name: dgc-db
    volumes:
      - .:/project
    environment:
      POSTGRES_DB: dgc
      POSTGRES_USER: dgc
      POSTGRES_PASSWORD: dgc
    ports:
      - 5432:5432
    build:
      context: ./db/

  dgc-adminer:
    image: adminer
    container_name: dgc-adminer
    links:
      - dgc-db:db
    ports:
      - 9003:8080

  #dgc-client:
    #image: dgc-client
    #container_name: dgc-client
    #entrypoint: "bash -c \"\
    #  cd /project/cli && \
    #  cargo build && \
    #  tail -f /dev/null \
    #  \""
    #volumes:
    #  - .:/project
    #  - ./keys:/root/.sawtooth/keys
    #build:
    #  context: ./cli

  dgc-tp:
    image: dgc-tp
    container_name: dgc-tp
    entrypoint: "bash -c \"\
        cd /project/tp/ && \
        cargo build && \
        dgc -vv -C tcp://validator:9004
        \""
    volumes:
      - .:/project
    build:
      context: ./tp

  dgc-sde-service:
    image: dgc-sde-service
    container_name: dgc-sde-service
    environment:
      DATABASE_URL: postgres://dgc:dgc@dgc-db:5432/dgc
    entrypoint: "bash -c \"
      cd /project/state_delta_export && \
      cargo build && \
      dgc-sde -vv -c tcp://validator:9004 \""
    volumes:
      - .:/project
    build:
      context: ./state_delta_export/
    depends_on:
      - validator
      - rest-api
      - dgc-db
