# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

[package]
name = "intkey"
version = "0.1.0"
authors = ["dgc.network"]

[dependencies]
#sabre-sdk = { path = "../../../../sdk" }
sabre-sdk = {git = "https://github.com/hyperledger/sawtooth-sabre"}

[lib]
crate-type = ["cdylib"]
