# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

# docker build -f cli/Dockerfile-installed-xenial -t sawtooth-pike-cli .

# -------------=== pike cli build ===-------------

FROM ubuntu:xenial as pike-cli-builder

ENV VERSION=AUTO_STRICT

RUN apt-get update \
 && apt-get install -y \
 curl \
 gcc \
 git \
 libssl-dev \
 libzmq3-dev \
 pkg-config \
 python3 \
 unzip

# For Building Protobufs
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
 && curl -OLsS https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip \
 && unzip protoc-3.5.1-linux-x86_64.zip -d protoc3 \
 && rm protoc-3.5.1-linux-x86_64.zip

ENV PATH=$PATH:/protoc3/bin
RUN /root/.cargo/bin/cargo install cargo-deb

COPY . /project

WORKDIR /project/cli

RUN export VERSION=$(../../../bin/get_version) \
 && sed -i -e s/version.*$/version\ =\ \"${VERSION}\"/ Cargo.toml \
 && /root/.cargo/bin/cargo deb --deb-version $VERSION

# -------------=== pike cli docker build ===-------------

FROM ubuntu:xenial

COPY --from=pike-cli-builder /project/cli/target/debian/pike-cli*.deb /tmp

RUN echo "deb [arch=amd64] http://repo.sawtooth.me/ubuntu/nightly xenial universe" >> /etc/apt/sources.list \
 && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 44FC67F19B2466EA \
 || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 44FC67F19B2466EA) \
 && apt-get update \
 && apt-get -f -y install \
    python3-sawtooth-cli \
    python3-sawtooth-sdk \
 && dpkg -i /tmp/pike-cli*.deb || true

ENTRYPOINT ["tail", "-f", "/dev/null"]
